# Generated by Django 5.1.1 on 2024-10-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0004_appointment_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
